services:
  - type: web
    name: smartbot_new
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python backend/app.py
    plan: free
    envVars:
      - key: OPENAI_API_KEY
        sync: false
