services:
  - type: web
    name: smartbot_new
    env: python
    region: frankfurt
    plan: free
    buildCommand: ""
    startCommand: "./start.sh"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
