services:
  - type: web
    name: smartbot_new
    env: python
    runtime: python3
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    autoDeploy: true
