services:
  - type: web
    name: smartbot_new
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "bash start.sh"
    envVars:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
