services:
  - type: web
    name: smartbot_new
    runtime: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python backend/app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
      - key: OPENAI_API_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: FLASK_ENV
        value: production
